// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrVldKrw9yTKGEuZMTYk491OZ9BVpjvKk',
    appId: '1:863316782489:web:3d2053e833b91855007708',
    messagingSenderId: '863316782489',
    projectId: 'chat-app-3b6b7',
    authDomain: 'chat-app-3b6b7.firebaseapp.com',
    storageBucket: 'chat-app-3b6b7.firebasestorage.app',
    measurementId: 'G-QMCPQ7FTX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUqyohi8OxfI7zj9juJzx1E9XLGc_39qA',
    appId: '1:863316782489:android:ea2581a1895ad441007708',
    messagingSenderId: '863316782489',
    projectId: 'chat-app-3b6b7',
    storageBucket: 'chat-app-3b6b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2nX_I2GN3_qQggGo-t9zj5wflp5waNXQ',
    appId: '1:863316782489:ios:ab3a76a50e8baba5007708',
    messagingSenderId: '863316782489',
    projectId: 'chat-app-3b6b7',
    storageBucket: 'chat-app-3b6b7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2nX_I2GN3_qQggGo-t9zj5wflp5waNXQ',
    appId: '1:863316782489:ios:ab3a76a50e8baba5007708',
    messagingSenderId: '863316782489',
    projectId: 'chat-app-3b6b7',
    storageBucket: 'chat-app-3b6b7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrVldKrw9yTKGEuZMTYk491OZ9BVpjvKk',
    appId: '1:863316782489:web:007a6c5961e3c455007708',
    messagingSenderId: '863316782489',
    projectId: 'chat-app-3b6b7',
    authDomain: 'chat-app-3b6b7.firebaseapp.com',
    storageBucket: 'chat-app-3b6b7.firebasestorage.app',
    measurementId: 'G-FRLGE27PRP',
  );
}
